default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dance_app_db_1mdv
  username: dance_app_db_1mdv_user
  password: mQ71l0LydigR2AAYbEeY2NBNbBHz9You
  host: dpg-cvdqhltumphs73bk5g3g-a.oregon-postgres.render.com
  port: 5432

test:
  <<: *default
  database: dance_app_db_1mdv_test
  username: dance_app_db_1mdv_user
  password: mQ71l0LydigR2AAYbEeY2NBNbBHz9You
  host: dpg-cvdqhltumphs73bk5g3g-a.oregon-postgres.render.com
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
